#!/bin/sh -e

export XDG_RUNTIME_DIR=/run/user/1000
export WAYLAND_DISPLAY=wayland-0

FLUTTER_TAG="$( (cd /usr/share/flutter/ && printf -- '%s\n' */) | head -n 1)"
export FLUTTER_TAG

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":/usr/share/flutter/"$FLUTTER_TAG"/release/lib/

/usr/bin/flutter-client -f -b /usr/share/flutter/ew_2026_flutter_demo/"$FLUTTER_TAG"/release/